Practice 5
Fastroof/NCTaskManager pull request #4
Opened 2021-10-30 23:23 UTC by Fastroof

2021-10-31 07:05 UTC, berestoleg88 requested changes

2021-10-31 07:05 UTC, berestoleg88 commented on src/main/java/ua/edu/sumdu/j2se/lytvynenko/tasks/AbstractTaskList.java
> +    public abstract AbstractTaskList incoming(int from, int to);
На скільки я пам'ятаю - реалізація цього методу повинна бути саме тут

2021-10-31 08:02 UTC, Fastroof commented on src/main/java/ua/edu/sumdu/j2se/lytvynenko/tasks/AbstractTaskList.java
> +    public abstract AbstractTaskList incoming(int from, int to);
Цитата з методички:
> Оскільки реалізація методу incoming не залежить від способу зберігання задач, його можна реалізувати в абстрактному класі AbstractTaskList

Але даний метод у мене залежить від способу зберігання, адже по різному потрібно проходити по елементам. Тому я і не зміг реалізувати один метод для всіх. Будь ласка, підскажіть як можна його реалізувати

2021-10-31 09:05 UTC, berestoleg88 commented on src/main/java/ua/edu/sumdu/j2se/lytvynenko/tasks/AbstractTaskList.java
> +    public abstract AbstractTaskList incoming(int from, int to);
Можна додати метод getType  в абстрактний класс і в залежності від того що він поверне викликати абстрактну фабрику, яка вже зробить ту чи іншу реалізацію

2021-11-03 17:02 UTC, Fastroof commented on src/main/java/ua/edu/sumdu/j2se/lytvynenko/tasks/AbstractTaskList.java
> +    public abstract AbstractTaskList incoming(int from, int to);
Додав метод getType та incoming

2021-11-04 06:29 UTC, berestoleg88 approved these changes

2021-11-04 07:05 UTC, merged